-- Example migration: run manually or via your migration runner
-- CREATE TABLE IF NOT EXISTS users (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   email VARCHAR(255) NOT NULL UNIQUE,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
